{{- if and .Values.gateway.enabled (not .Values.gateway.gatewayName) -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "httpbin.fullname" . }}
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- toYaml .Values.gateway.listeners | nindent 4 }}
---
{{- end }}
{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "httpbin.fullname" . }}
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.gatewayName | default (include "httpbin.fullname" .) }}
      namespace: {{ .Values.gateway.gatewayNamespace | default .Release.Namespace }}
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ .host | quote }}
  {{- end }}
  rules:
    {{- range .Values.gateway.hosts }}
    {{- range .paths }}
    - matches:
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      backendRefs:
        - name: {{ include "httpbin.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
    {{- end }}
{{- end }}