{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "httpbin.fullname" . }}
  annotations: {}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ tpl ( include "httpbin.fullname" . ) . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    {{- tpl (toYaml .Values.keda.triggers) . | nindent 4 }}
{{- end }}
