{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: podDisruptionBudget
metadata:
  name: {{ include "httpbin.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "httpbin.labels" . | nindent 6 }}
{{- end }}