apiVersion: v2
name: minio
version: 0.1.2
appVersion: "latest"
type: application
description: A Helm chart for Kubernetes, featuring MinIO. Special thanks to cleanstart/minio and georgmangold/console for their excellent work.
sources:
  - https://hub.docker.com/r/cleanstart/minio
  - https://github.com/georgmangold/console/tree/main
annotations:
  "artifacthub.io/thanks": |
    - name: cleanstart/minio
      url: https://hub.docker.com/r/cleanstart/minio
    - name: georgmangold/console
      url: https://github.com/georgmangold/console
keywords:
  - minio
  - storage
  - object-storage
  - s3