apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}-console
  labels:
    {{- include "minio.console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio.console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.console.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "minio.console.labels" . | nindent 8 }}
{{- with .Values.console.podLabels }}
        {{- toYaml . | nindent 8 }}
{{- end }}

    spec:
{{- with .Values.console.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "minio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.console.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.console.securityContext | nindent 12 }}
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            {{- tpl (toYaml .Values.console.env) . | nindent 12 }}
              
{{- with .Values.console.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.console.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
