apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
data:
  MINIO_ROOT_PASSWORD: {{ .Values.minio.minio_root_password | b64enc }}
