apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.minio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "minio.labels" . | nindent 8 }}
{{- with .Values.minio.podLabels }}
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- with .Values.minio.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "minio.serviceAccountName" . }}
{{- with .Values.minio.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.minio.buckets }}
      initContainers:
        - name: create-bucket
          image: busybox:1.37
  {{- with $.Values.minio.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
  {{- end }}
          command: ['sh', '-c', "cd /data/ && mkdir {{- range $.Values.minio.buckets }} {{ . }}{{- end }}"]
          volumeMounts:
          - name: data
            mountPath: /data
{{- end }}
      containers:
        - name: minio
{{- with .Values.minio.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
{{- end }}
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          ports:
{{- range $k, $v := .Values.minio.service }}
            - name: {{ $k }}
              containerPort: {{ $v.port }}
              protocol: TCP
{{- end }}
{{- with .Values.minio.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.minio.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.minio.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
{{- end }}
          args: {{ .Values.minio.args | toJson }}
          volumeMounts:
          - name: data
            mountPath: /data
          env:
            - name: "MINIO_ROOT_USER"
              value: {{ .Values.minio.minio_root_user }}
            - name: "MINIO_REGION_NAME"
              value: {{ .Values.minio.minio_region_name }}
            - name: "MINIO_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: "MINIO_ROOT_PASSWORD"
{{- with .Values.minio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.minio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.minio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{ .Values.minio.persistentStorage.accessModes | toJson }}
      storageClassName: {{ .Values.minio.persistentStorage.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.minio.persistentStorage.size }}
