apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redmine.fullname" . }}-database
  labels:
    {{- include "redmine.labels" . | nindent 4 }}
data:
  REDMINE_DB_POSTGRES: "{{ .Release.Name }}-postgresql"
  REDMINE_DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  REDMINE_DB_DATABASE: {{ .Values.postgresql.auth.database | quote }}
  REDMINE_DB_DATABASE: redmine
  REDMINE_DB_ENCODING: utf8
  REDMINE_PLUGINS_MIGRATE: {{ .Values.redmine.env.REDMINE_PLUGINS_MIGRATE | quote }}
  SECRET_KEY_BASE: "supersecretkey"