apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redmine.fullname" . }}-secrets
type: Opaque
data:
  REDMINE_DB_PASSWORD: {{ .Values.redmine.env.REDMINE_DB_PASSWORD | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.redmine.env.SECRET_KEY_BASE | b64enc | quote }}