---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redmine.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.redmine.tls.crt | b64enc }}
  tls.key: {{ .Values.redmine.tls.key | b64enc }}
