#
# Default values for devpi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

# -- Number of replicas. More information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

## Image configuration
image:
  # -- Image repository
  repository: owanio1992/devpi
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Secrets for pulling an image from a private repository. More information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# -- Override the chart name.
nameOverride: ""
# -- Override the full name.
fullnameOverride: ""

## Service account configuration. More information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for the pod. For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# -- Labels for the pod. For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# -- Pod security context
# e.g.
# fsGroup: 2000
podSecurityContext:
  {}

# -- Container security context
# e.g.
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
securityContext:
  {}

## Service configuration. More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # -- Service type. More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # -- Service port. More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3141

## Ingress configuration. More information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  # -- If you want to use ingress, please ensure not to use round-robin mode
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Ingress annotations
  annotations: {}
    # haproxy.org/load-balance: "source"  
  # -- Ingress hosts
  hosts: []
    # - host: devpi.chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []

# -- Resource requests and limits
# e.g.
# limits:
#   cpu: 2
#   memory: 4Gi
# requests:
#   cpu: 0
#   memory: 0
resources: {}

# -- Liveness and readiness probes configuration. More information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# -- Node selector for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Affinity for pod assignment
affinity: {}

# -- Arguments to pass to the container
args: [
    "--login",
    "-c",
    "
    devpi-init;
    devpi-server --host=0.0.0.0 --threads=300
    ",
  ]

## Persistent storage configuration
persistentStorage:
  # -- Storage class name for persistent volume
  storageClassName: "local-path"
  # -- Size of the persistent volume
  size: "5Gi"
